


# Visualization
GRID_SIZE = (25, 25)
FONT_SIZE = 35


# Arena Set Up
# CELL_RATIO = 0.35
# BRAIN_TYPE = 'Network'

FOOD_RATIO = 0.1

# Repopulation Controls
REPOP_THRESHOLD = 0.05
PERCENT_SPACES_TO_FILL_CELLS = 0.3
PERCENT_SPACES_TO_FILL_FOOD  = 0.1
MUTATION_PROBABILITY = 0.05

# Action Costs
OOB_ATTEMPT_COST = 5
MOVE_COST = 3
STAB_COST = 10
FAIL_EAT_COST = 3
EAT_SUCCESS_BENEFIT = 10
REPRODUCE_COST = 2
CATCHALL_COST = 3
